#+TITLE: My Literate Emacs Configuration
#+AUTHOR: Simen Omholt-Jensen
#+STARTUP:     hidestars overview
#+PROPERTIES: header-args:emacs-lisp :tangle "~/.emacs.d/init.el"

[[https://github.com/simenojensen/.emacs.d/blob/master/my-literate-emacs-configuration.org][My Configs]]

* Start up
** Lexical Binding

#+begin_quote
Until Emacs 24.1 (June 2012), Elisp only had dynamically scoped variables, a
feature, mostly by accident, common to old lisp dialects. While dynamic scope
has some selective uses, it’s widely regarded as a mistake for local variables,
and virtually no other languages have adopted it.
#+end_quote

[[https://nullprogram.com/blog/2016/12/22/][More Information]]

#+begin_src emacs-lisp
  ;;; init.el --- -*- lexical-binding: t -*-
#+end_src

** Avoid Garbage Collection at Startup

#+begin_quote
The GC can easily double startup time, so we suppress it at startup by turning
up =gc-cons-threshold= (and perhaps =gc-cons-percentage=) temporarily:
#+end_quote

[[https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-does-doom-start-up-so-quickly][More Information]]

#+begin_src emacs-lisp
  (setq gc-cons-threshold most-positive-fixnum ; 2^61 bytes
        gc-cons-percentage 0.6)
#+end_src

** Benchmarking

First, declare a hook which will benchmark the startup process. It reports how
long the it took to start up, and how many garbage collections were performed.

[[https://blog.d46.us/advanced-emacs-startup/][More Information]]

#+begin_src emacs-lisp
  (add-hook 'emacs-startup-hook
            (lambda ()
              (message "Emacs ready in %s with %d garbage collections."
                       (format "%.2f seconds"
                               (float-time
                                (time-subtract after-init-time before-init-time)))
                       gcs-done)))
#+end_src

** Unset =file-name-handler-alist=

Every file opened and loaded by Emacs will run through this list to check for a
proper handler for the file, but during startup, it won’t need any of them.

#+begin_src emacs-lisp
  (defvar file-name-handler-alist-original file-name-handler-alist)
  (setq file-name-handler-alist nil)
#+end_src

* Garbage Collection
** Set =gc-cons-threshold= Smaller for Interactive Use

A large =gc-cons-threshold= may cause freezing and stuttering during long-term
interactive use. If you experience freezing, decrease this amount, if you
increase stuttering, increase this amount.

#+begin_src emacs-lisp
  (defvar better-gc-cons-threshold 100000000 ; 100mb
    "The default value to use for `gc-cons-threshold'.
     If you experience freezing, decrease this.  If you experience stuttering, increase this.")

  (add-hook 'emacs-startup-hook
            (lambda ()
              (setq gc-cons-threshold better-gc-cons-threshold)
              (setq file-name-handler-alist file-name-handler-alist-original)
              (makunbound 'file-name-handler-alist-original)))
#+end_src

Garbage Collect when Emacs is out of focus and avoid garbage collection when
using minibuffer.

#+begin_src emacs-lisp
  (add-hook 'emacs-startup-hook
            (lambda ()
              (if (boundp 'after-focus-change-function)
                  (add-function :after after-focus-change-function
                                (lambda ()
                                  (unless (frame-focus-state)
                                    (garbage-collect))))
                (add-hook 'after-focus-change-function 'garbage-collect))
              (defun gc-minibuffer-setup-hook ()
                (setq gc-cons-threshold (* better-gc-cons-threshold 2)))

              (defun gc-minibuffer-exit-hook ()
                (garbage-collect)
                (setq gc-cons-threshold better-gc-cons-threshold))

              (add-hook 'minibuffer-setup-hook #'gc-minibuffer-setup-hook)
              (add-hook 'minibuffer-exit-hook #'gc-minibuffer-exit-hook)))
#+end_src

* Package Management
** =straight.el=

[[https://github.com/raxod502/straight.el#getting-started][More Information]]

#+begin_src emacs-lisp
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+end_src

*** =use-package= integration
[[https://github.com/raxod502/straight.el#getting-started][More Information]]

#+begin_src emacs-lisp
  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t)
#+end_src

** =package-enable-at-startup=

Set =package-enable-at-startup= to =nil= to prevent superfluous loading of packages.

[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Package-Installation.html][More Information]]

#+begin_src emacs-lisp
  (setq-default package-enable-at-startup nil)
#+end_src

** Prefer Newer =.el= Files Over Older =.elc= Files.

#+begin_src emacs-lisp
  (setq-default load-prefer-newer t)
#+end_src

** Automatically Compile Packages During Startup.

[[https://github.com/emacscollective/auto-compile][More Information]]

#+begin_src emacs-lisp
  (use-package auto-compile
    :config
    (auto-compile-on-load-mode)
    (auto-compile-on-save-mode))
#+end_src

** =bind-key=

To use with =use-package=.

#+begin_src emacs-lisp
  (use-package bind-key)
#+end_src

** =diminish=

The =diminish= package makes it possible to remove clutter from the modeline. The =:diminish= keyword in the =use-package= declarations signify =diminish= invocation.

[[https://github.com/myrjola/diminish.el][More Information]]

#+begin_src emacs-lisp
  (use-package diminish)
#+end_src

** =try=

The =try= package let's you try new packages without installed them. On the next restart of Emacs, they are not loaded.

[[https://github.com/larstvei/Try][More Information]]

#+begin_src emacs-lisp
  (use-package try)
#+end_src

* Global Functionalities
** User Information
#+begin_src emacs-lisp
  (setq user-full-name "Simen Omholt-Jensen")
  (setq user-mail-address "simen@omholt-jensen.com")
#+end_src

** Convenient Default Settings

#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))                       ;; Fancy titlebar for MacOS
  (add-to-list 'default-frame-alist '(ns-appearance . dark))                              ;; Fancy titlebar for MacOS
  (setq ns-use-proxy-icon  nil)                                                           ;; Fancy titlebar for MacOS
  (setq frame-title-format '(:eval (if (buffer-file-name)                                 ;; Set frame title to *Buffer/File Name*
                                       (abbreviate-file-name (buffer-file-name)) "%b")))
  (set-language-environment "UTF-8")                                                      ;; Set enconding language
  (set-default-coding-systems 'utf-8)                                                     ;; Set enconding language
  (prefer-coding-system 'utf-8)                                                           ;; Set enconding language
  (set-terminal-coding-system 'utf-8)                                                     ;; Set enconding language
  (set-keyboard-coding-system 'utf-8)                                                     ;; Set enconding language
  (global-display-line-numbers-mode)                                                      ;; Display line numbers
  (setq-default read-process-output-max (* 1024 1024))                                    ;; Increase the amount of data which Emacs reads from the process
  (dolist (mode '(vterm-mode-hook
                  jupyter-repl-mode-hook))                                                       ;; disable line number for some modes
    (add-hook mode (lambda () (display-line-numbers-mode 0))))
  (setq-default fill-column 80)                                                           ;; Set fill column to 80 chars by default
  (setq-default column-number-mode t)                                                     ;; Display column numbers
  (dolist (mode '(org-mode-hook                                                           ;; Disable line numbers for some modes
                  term-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))
  (setq-default inhibit-startup-screen t)                                                 ;; Don't show the startup message
  (setq inhibit-startup-echo-area-message t)                                              ;; Don't show the startup echo message
  (setq-default initial-scratch-message nil)                                              ;; Set initial scratch message to nil
  (set-fringe-mode 10)                                                                    ;; Give some breathing room
  (set-default 'truncate-lines t)                                                         ;; default truncate lines
  (setq debug-on-error nil)                                                               ;; Receive more information errors
  (setq custom-file "~/.emacs.d/custom.el")
  (ignore-errors (load custom-file))                                                      ;; Load custom.el if it exists
  (setq-default create-lockfiles nil)                                                     ;; Disable lock files
  (setq-default backup-directory-alist '(("." . "/Users/simenojensen/.emacs.d/backups"))) ;; Save backup files
  (setq-default indent-tabs-mode nil)                                                     ;; Don't use hard tabs
  (setq echo-keystrokes 0.1)                                                              ;; Echo keystrokes fast
  (fset 'yes-or-no-p 'y-or-n-p)                                                           ;; y-or-n instead of yes-or-no
  (add-hook 'before-save-hook 'delete-trailing-whitespace)                                ;; Delete trailing whitespace on save
  (setq require-final-newline t)                                                          ;; Add a newline at end of file on save
  (global-auto-revert-mode t)                                                             ;; Automatically update buffers if a file content has changed on disk

  (save-place-mode t)                                                                     ;; Save position of the point in file
  (global-hl-line-mode t)                                                                 ;; Highlight the line with the point
  (add-hook 'before-save-hook 'time-stamp)                                                ;; Update timestamp of 8 first lines on save
  (setq large-file-warning-threshold 100000000)                                           ;; Warn when opening file larger than 100 MB
  (desktop-save-mode 1)                                                                   ;; save desktop
  (setq history-delete-duplicates t)                                                      ;; delete duplicate history
  (setq revert-without-query '(".*"))                                                     ;; do not ask when reverting buffer
  (setq-default cursor-type '(bar . 4))                                                   ;; use bar for cursort
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)                                 ;; Cancel on escape
#+end_src

** Smooth Scrolling

Configurations for smooth scrolling

#+begin_src emacs-lisp
  ;; Vertical Scroll
  (setq scroll-step 1)
  (setq scroll-margin 1)
  (setq scroll-conservatively 101)
  (setq scroll-up-aggressively 0.01)
  (setq scroll-down-aggressively 0.01)
  (setq auto-window-vscroll nil)
  (setq fast-but-imprecise-scrolling nil)
  (setq mouse-wheel-scroll-amount '(1 ((shift) . 1)))
  (setq mouse-wheel-progressive-speed nil)
  ;; Horizontal Scroll
  (setq hscroll-step 1)
  (setq hscroll-margin 1)
#+end_src

** Disable GUIs

#+begin_src emacs-lisp
  (menu-bar-mode -1)                         ;; Disable menu bar
  (tool-bar-mode -1)                         ;; Disable tool bar
  (scroll-bar-mode -1)                       ;; Disable scroll bar
  (blink-cursor-mode -1)                     ;; Disable blinking cursor
  (setq-default ring-bell-function 'ignore)  ;; Disable bell function
#+end_src

** Killing Emacs

#+begin_src emacs-lisp
  (setq-default confirm-kill-emacs nil)        ;; Do not confirm when killing Emacs
  (setq-default confirm-kill-processes nil)    ;; do not confirm when killing processes before killing Emacs
#+end_src

* OS Specific Settings

Detect which OS Emacs is being run on, and configure keybindings accordingly.

#+begin_src emacs-lisp :noweb tangle
  (cond ((eq system-type 'darwin)
         <<macOS>>
         )
        ((eq system-type 'windows-nt)
         <<Windows>>
         )
        ((eq system-type 'gnu/linux)
         <<Linux>>
         ))
#+end_src

** macOS
Remap mac modifier keys to emacs modifier sequences.

#+begin_src emacs-lisp :tangle no :noweb-ref macOS
  (customize-set-variable 'mac-command-modifier 'meta)
  (customize-set-variable 'mac-right-command-modifier 'super)
  (customize-set-variable 'mac-option-modifier 'alt)
  (customize-set-variable 'mac-right-option-modifier 'hyper)
#+end_src

Next, we are binding ~M-=~ to increase the font size, and ~M--~ to decrease the font
size.

#+begin_src emacs-lisp :tangle no :noweb-ref macOS
  (bind-key "M-=" 'text-scale-increase)
  (bind-key "M--" 'text-scale-decrease)
#+end_src

Use ~M-`~ to switch focus between frames

#+begin_src emacs-lisp :tangle no :noweb-ref macOS
  (bind-key "M-`" 'other-frame)
#+end_src
Make sure the =$PATH= is loaded from the default shell.

[[https://github.com/purcell/exec-path-from-shell][More Information]]

#+begin_src emacs-lisp :tangle no :noweb-ref macOS
  (use-package exec-path-from-shell
    :config
    (setq shell-file-name "/usr/local/bin/zsh") ;; Let emacs know which shell to use.
    (setq exec-path-from-shell-variables  '("PATH" "MANPATH" "VIRTUAL_ENV" "PKG_CONFIG_PATH" "GOPATH"))
    (if (string-equal system-type "darwin")
        (exec-path-from-shell-initialize)))
#+end_src

** Windows

Not implemented

#+begin_src emacs-lisp :tangle no :noweb-ref Windows

#+end_src

** Linux

Not implemented

#+begin_src emacs-lisp :tangle no :noweb-ref Linux

#+end_src

* Keybindings
** which-key

The =which-key= package automatically displays potential command information as command keys are typed. This makes it easy to explore Emacs functionality.

[[https://github.com/justbur/emacs-which-key][More Information]]

#+begin_src emacs-lisp
  (use-package which-key
    :diminish which-key-mode
    :config
    (setq which-key-idle-delay 0.5)
    (setq which-key-frame-max-height 40)
    (which-key-mode))
#+end_src

** =bind-key=
*** Window Adjustment

#+begin_src emacs-lisp
  (bind-key "s-<left>" 'shrink-window-horizontally)
  (bind-key "s-<right>" 'enlarge-window-horizontally)
  (bind-key "s-<down>" 'shrink-window)
  (bind-key "s-<up>" 'enlarge-window)
  (unbind-key "C-v" global-map) ;; disable annoying scroll window
#+end_src

*** Truncate Lines

#+begin_src emacs-lisp
  (bind-key "C-x C-l" 'toggle-truncate-lines)
#+end_src

*** Motion

#+begin_src emacs-lisp
  (bind-key "M-p" 'backward-paragraph)
  (bind-key "M-n" 'forward-paragraph)
  (bind-key "M-g" 'goto-line)
#+end_src

*** ibuffer

#+begin_src emacs-lisp
  (bind-key "C-x b" 'ibuffer-other-window)
  (bind-key "C-x C-b" 'switch-to-buffer)
#+end_src

*** set column fill
#+begin_src emacs-lisp
(unbind-key "C-x f" global-map)
#+end_src

* Interface Enhancement
** =crux=

=crux= is Collection of Ridiculously Useful eXtensions for Emacs.

[[https://github.com/bbatsov/crux][More Information]]

#+begin_src emacs-lisp
  (use-package crux
    :bind
    ("C-a" . crux-move-beginning-of-line)
    :config
    (defalias 'rename-file-and-buffer #'crux-rename-file-and-buffer))
#+end_src

** =Ivy= / =Counsel= / =Swiper= / =amx=

=Ivy= is an interactive interface for completion in Emacs.

[[https://oremacs.com/swiper/][More Information]]

=amx= prioritizes your most used commands

[[https://github.com/DarwinAwardWinner/amx][More Information]]

#+begin_src emacs-lisp
  (use-package ivy
    :diminish
    :init
    (use-package amx)
    (use-package counsel :diminish :config (counsel-mode 1))
    (use-package swiper)
    (ivy-mode 1)
    :bind
    (("C-x C-f" . counsel-find-file)
     ("C-x f". counsel-fzf)
     ("C-h f" . counsel-describe-function)
     ("C-h v" . counsel-describe-variable)
     ("C-h l" . counsel-find-library)
     ("C-h i" . counsel-info-lookup-symbol)
     ("C-h u" . counsel-unicode-char)
     ("C-c k" . counsel-rg)
     ("C-x l" . counsel-locate)
     ("M-x" . counsel-M-x)
     ("M-v" . counsel-yank-pop)
     ("C-s" . swiper-isearch)
     :map ivy-minibuffer-map
     ("A-<tab>" . ivy-mark) ;; Mark multiple candidates
     ("C-<return>" . ivy-call) ;; perform call
     )
    :config
    (ivy-mode 1)
    (setq ivy-height 20)
    (setq ivy-initial-inputs-alist nil)
    (setq ivy-display-style 'fancy)
    (setq counsel-switch-buffer-preview-virtual-buffers nil)
    ;; (setq ivy-use-virtual-buffers t)
    (setq ivy-count-format "(%d/%d) "))
#+end_src

** =ivy-posframe=
ivy-posframe is a ivy extension, which let ivy use posframe to show its candidate menu.
[[https://github.com/tumashu/ivy-posframe][More Information]]

#+begin_src emacs-lisp :tangle no
  (use-package ivy-posframe
    :config
    ;; (setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display)))
    (setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display-at-frame-center)))
    ;; (setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display-at-window-center)))
    ;; (setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display-at-frame-bottom-left)))
    ;; (setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display-at-window-bottom-left)))
    ;; (setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display-at-frame-top-center)))
    (ivy-posframe-mode 1))
#+end_src

** =helpful=

Helpful is an alternative to the built-in Emacs help that provides much more contextual information.
[[https://github.com/Wilfred/helpful][More Information]]

#+begin_src emacs-lisp
  (use-package helpful
    :bind
    ([remap describe-function] . helpful-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . helpful-variable)
    ([remap describe-key] . helpful-key)
    :config
    (setq counsel-describe-function-function #'helpful-callable)
    (setq counsel-describe-variable-function #'helpful-variable))
#+end_src

** =undo-tree=

=undo-tree=, a feature that provides a visualization of the undos in a file.

[[https://www.emacswiki.org/emacs/UndoTree][More Information]]

#+begin_src emacs-lisp
  (use-package undo-tree
    :diminish undo-tree-mode
    :init
    (global-undo-tree-mode)
    :config
    (setq undo-tree-history-directory-alist '(("." . "~/.emacs.d/undo")))
    (setq undo-tree-visualizer-diff t)
    (setq undo-tree-visualizer-timestamps t))
#+end_src

** =color-rg=

=color rg= is a search and refactoring tool based on *ripgrep*.

[[https://github.com/manateelazycat/color-rg][More Information]]

#+begin_src emacs-lisp
  (use-package color-rg
    :straight
    (color-rg :type git :host github :repo "manateelazycat/color-rg")
    :bind
    ("C-M-s" . color-rg-search-input))
#+end_src

** =Dired=

=Dired= is the built-in directory editor

[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html][More Information]]

#+begin_src emacs-lisp
    (use-package dired
      :straight nil
      :bind
      (("C-x C-j" . dired-jump)
       ("C-x j" . dired-jump-other-window))
      :custom
      ;; Always delete and copy recursively
      (dired-recursive-deletes 'always)
      (dired-recursive-copies 'always)
      ;; Auto refresh Dired, but be quiet about it
      (global-auto-revert-non-file-buffers t)
      (auto-revert-verbose nil)
      ;; Quickly copy/move file in Dired
      (dired-dwim-target t)
      ;; Move files to trash when deleting
      (delete-by-moving-to-trash t)
      (trash-directory "~/.Trash")
      ;; Load the newest version of a file
      (load-prefer-newer t)
      ;; Detect external file changes and auto refresh file
      (auto-revert-use-notify nil)
      (auto-revert-interval 3) ; Auto revert every 3 sec
      :config
      ;; Enable global auto-revert
      (global-auto-revert-mode t)
      ;; sort directory first
      (setq insert-directory-program "/usr/local/bin/gls"
            dired-use-ls-dired t)
      (setq dired-listing-switches "-laXGh --group-directories-first")
      ;; Reuse same dired buffer, to prevent numerous buffers while navigating in dired
      (put 'dired-find-alternate-file 'disabled nil)
      :hook
      (dired-mode . (lambda ()
                      (local-set-key (kbd "<mouse-2>") #'dired-find-alternate-file)
                      (local-set-key (kbd "RET") #'dired-find-alternate-file)
                      (local-set-key (kbd "^")
                                     (lambda () (interactive) (find-alternate-file ".."))))))
#+end_src

** =disk-usage=

=disk-usage= is a file system analyzer that offers a tabulated view of file listings sorted by size.

[[https://gitlab.com/ambrevar/emacs-disk-usage][More Information]]

#+begin_src emacs-lisp
  (use-package disk-usage)
#+end_src

** =restart-emacs=

=restart-emacs= is a simple emacs package to restart emacs from within emacs.

[[https://github.com/iqbalansari/restart-emacs][More Information]]

#+begin_src emacs-lisp
  (use-package restart-emacs)
#+end_src

* Navigation
** =ace-window=

=ace-window= offers fast window navigation with [[https://github.com/zamansky/using-emacs/blob/master/myinit.org#ace-windows-for-easy-window-switching][customizable]] prompts.

[[https://github.com/abo-abo/ace-window][More Information]]

#+begin_src emacs-lisp
  (use-package ace-window
    :bind
    ("C-x C-o" . ace-window)
    ("C-x o" . ace-window)
    :init
    (custom-set-faces
     '(aw-leading-char-face
       ((t (:inherit fixed-pitch :height 4.0 :foreground "firebrick3"))))))
#+end_src

** =winner-mode=

Built-in =winner-mode= for remembering previous window actions.

#+begin_src emacs-lisp
  (winner-mode 1)
#+end_src

* Console
** =vterm=
Emacs-libvterm (vterm) is fully-fledged terminal emulator inside GNU Emacs based on libvterm, a C library. As a result of using compiled code (instead of elisp), emacs-libvterm is fully capable, fast, and it can seamlessly handle large outputs.
[[https://github.com/akermu/emacs-libvterm][More Information]]

=multi-vterm=
[[https://github.com/suonlight/multi-vterm][More Information]]

#+begin_src emacs-lisp
  (use-package vterm
    ;; add functionality for counsel-yank-pop
    :after counsel
    :init
    ;; Counsel-yank-pop
    (defun vterm-counsel-yank-pop-action (orig-fun &rest args)
      (if (equal major-mode 'vterm-mode)
          (let ((inhibit-read-only t)
                (yank-undo-function (lambda (_start _end) (vterm-undo))))
            (cl-letf (((symbol-function 'insert-for-yank)
                       (lambda (str) (vterm-send-string str t))))
              (apply orig-fun args)))
        (apply orig-fun args)))

    (advice-add 'counsel-yank-pop-action :around #'vterm-counsel-yank-pop-action)
    (setq vterm-max-scrollback 10000)
    (setq vterm-always-compile-module t)
    )
  ;; (use-package multi-vterm)
#+end_src

* General Programming
** =magit=

Magit is an interface to the version control system Git, implemented as an Emacs package. Magit aspires to be a complete Git porcelain.

[[https://magit.vc/][More Information]]

#+begin_src emacs-lisp
  (use-package magit
    :bind
    ("C-x g" . magit-status))
#+end_src

** =projectile=

Projectile is a project interaction library for Emacs.

[[https://docs.projectile.mx/projectile/index.html][More Information]]

#+begin_src emacs-lisp
  (use-package projectile
    :diminish
    :config
    (define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
    (setq projectile-completion-system 'ivy)
    (projectile-mode +1))
#+end_src

** =treemacs=

=treemacs= is a file and project explorer similar to NeoTree or vim’s NerdTree, but largely inspired by the Project Explorer in Eclipse.

[[https://github.com/Alexander-Miller/treemacs][More Information]]

#+begin_src emacs-lisp
  (use-package treemacs
    :defer t
    :init
    (with-eval-after-load 'winum
      (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
    :config
    (progn
      (setq treemacs-collapse-dirs                 (if treemacs-python-executable 3 0)
            treemacs-deferred-git-apply-delay      0.5
            treemacs-directory-name-transformer    #'identity
            treemacs-display-in-side-window        t
            treemacs-eldoc-display                 t
            treemacs-file-event-delay              5000
            treemacs-file-extension-regex          treemacs-last-period-regex-value
            treemacs-file-follow-delay             0.2
            treemacs-file-name-transformer         #'identity
            treemacs-follow-after-init             t
            treemacs-expand-after-init             t
            treemacs-git-command-pipe              ""
            treemacs-goto-tag-strategy             'refetch-index
            treemacs-indentation                   2
            treemacs-indentation-string            " "
            treemacs-is-never-other-window         nil
            treemacs-max-git-entries               5000
            treemacs-missing-project-action        'ask
            treemacs-move-forward-on-expand        nil
            treemacs-no-png-images                 nil
            treemacs-no-delete-other-windows       t
            treemacs-project-follow-cleanup        nil
            treemacs-persist-file                  (expand-file-name ".cache/treemacs-persist" user-emacs-directory)
            treemacs-position                      'left
            treemacs-read-string-input             'from-child-frame
            treemacs-recenter-distance             0.1
            treemacs-recenter-after-file-follow    nil
            treemacs-recenter-after-tag-follow     nil
            treemacs-recenter-after-project-jump   'always
            treemacs-recenter-after-project-expand 'on-distance
            treemacs-litter-directories            '("/node_modules" "/.venv" "/.cask")
            treemacs-show-cursor                   nil
            treemacs-show-hidden-files             t
            treemacs-silent-filewatch              nil
            treemacs-silent-refresh                nil
            treemacs-sorting                       'alphabetic-asc
            treemacs-space-between-root-nodes      t
            treemacs-tag-follow-cleanup            t
            treemacs-tag-follow-delay              1.5
            treemacs-user-mode-line-format         nil
            treemacs-user-header-line-format       nil
            treemacs-width                         35
            treemacs-workspace-switch-cleanup      nil)

      ;; The default width and height of the icons is 22 pixels. If you are
      ;; using a Hi-DPI display, uncomment this to double the icon size.
      ;;(treemacs-resize-icons 44)

      (treemacs-follow-mode t)
      (treemacs-filewatch-mode t)
      (treemacs-fringe-indicator-mode 'always)
      (pcase (cons (not (null (executable-find "git")))
                   (not (null treemacs-python-executable)))
        (`(t . t)
         (treemacs-git-mode 'deferred))
        (`(t . _)
         (treemacs-git-mode 'simple))))
    :bind
    (:map global-map
          ("M-0"       . treemacs-select-window)
          ("C-x t 1"   . treemacs-delete-other-windows)
          ("C-x t t"   . treemacs)
          ("C-x t B"   . treemacs-bookmark)
          ("C-x t C-t" . treemacs-find-file)
          ("C-x t M-t" . treemacs-find-tag)))

  (use-package treemacs-projectile
    :after (treemacs projectile))

  (use-package treemacs-icons-dired
    :after (treemacs dired)
    :config (treemacs-icons-dired-mode))

  (use-package treemacs-magit
    :after (treemacs magit))
#+end_src

** =iedit=

=iedit= allows you to edit multiple occurrences of a symbol or region.

[[https://www.emacswiki.org/emacs/Iedit][More Information]]

#+begin_src emacs-lisp :tangle no
  (use-package iedit
    :bind
    ("M-;" . iedit-mode))
#+end_src

** =format-all=

=format-all= let one auto-format source code in many languages using the same command.
[[https://github.com/lassik/emacs-format-all-the-code][More Information]]

#+begin_src emacs-lisp
  (use-package format-all
    :hook
    (prog-mode . format-all-mode)
    (format-all-mode . format-all-ensure-formatter)
    )
#+end_src

** =evil-nerd-commenter=

=evil-nerd-commenter= lets one comment/uncomment lines efficiently. Like Nerd Commenter in VIM

[[https://github.com/redguardtoo/evil-nerd-commenter][More Information]]

#+begin_src emacs-lisp
  (use-package evil-nerd-commenter
    :bind
    ("C-;" . evilnc-comment-or-uncomment-lines))
#+end_src

** =yasnippets=

#+begin_src emacs-lisp
  (use-package yasnippet
    :diminish yas-minor-mode
    :init (use-package yasnippet-snippets :after yasnippet)
    :config
    (yas-global-mode 1))
#+end_src

** =flycheck=

Flycheck is a modern on-the-fly syntax checking extension for GNU Emacs, intended as replacement for the older Flymake extension which is part of GNU Emacs.

[[https://www.flycheck.org/en/latest/][More Information]]

#+begin_src emacs-lisp
  (use-package flycheck
    :diminish
    :init
    (global-flycheck-mode)
    :hook
    (prog-mode . flycheck-mode)
    :config
    (setq flycheck-checker-error-threshold 1000)
    )
#+end_src

** =expand-region=
[[https://github.com/magnars/expand-region.el][More Information]]

#+begin_src emacs-lisp
  (use-package expand-region
    :bind ("C-=" . er/expand-region))
#+end_src

** =lsp-mode=

 LSP Mode - Language Server Protocol support for Emacs
 Language Server Protocol support with multiples languages support for Emacs

 [[https://emacs-lsp.github.io/lsp-mode/][More Information]]

#+begin_src emacs-lisp
  (use-package lsp-mode
    :init
    ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
    (setq lsp-keymap-prefix "C-c l")
    :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
           (html-mode . lsp-deferred)
           (json-mode . lsp-deferred)
           (python-mode . lsp-deferred)
           (c++-mode . lsp-deferred)
           (go-mode . lsp-deferred)
           (java-mode . lsp-deferred)
           ;; if you want which-key integration
           (lsp-mode . lsp-enable-which-key-integration)
           (lsp-mode . (lambda ()
                         (bind-key "M-;" 'lsp-rename lsp-mode-map))))
    :commands lsp
    :config
    (setq lsp-idle-delay 0.5)
    (setq lsp-log-io nil) ; if set to true can cause a performance hit
    ;; symbol highlighting
    (setq lsp-enable-symbol-highlighting t)
    ;; lenses
    (setq lsp-lens-enable nil)
    ;; headerline
    (setq lsp-headerline-breadcrumb-enable t)
    ;; modeline
    (setq lsp-modeline-code-actions-enable nil)
    (setq lsp-modeline-diagnostics-enable t)
    ;; linter
    (setq lsp-diagnostics-provider :auto) ;; prefer flycheck, fallback to flymake
    ;; eldoc
    (setq lsp-eldoc-enable-hover nil)
    (setq lsp-eldoc-render-all t)
    ;; signatures
    (setq lsp-signature-auto-activate nil)
    (setq lsp-signature-render-documentation nil)
    ;; completion
    (setq lsp-completion-provider :capf)
    (setq lsp-completion-show-detail t)
    (setq lsp-completion-show-kind t)
    )
#+end_src

*** =lsp-ui=

 UI integrations for lsp-mode

 [[https://emacs-lsp.github.io/lsp-ui/][More Information]]

#+begin_src emacs-lisp
  (use-package lsp-ui
    :commands lsp-ui-mode
    :bind
    ;; lsp-ui-peek
    ((:map lsp-ui-mode-map
           ([remap xref-find-definitions] . lsp-ui-peek-find-definitions)
           ([remap xref-find-references] . lsp-ui-peek-find-references)
           ("C-c d" . lsp-ui-doc-show)
           ))
    :config
    ;; show docs
    (setq lsp-ui-doc-enable t)
    (setq lsp-ui-doc-show-with-cursor nil)
    (setq lsp-ui-doc-show-with-mouse t)
    ;; sideline
    (setq lsp-ui-sideline-enable t)
    (setq lsp-ui-sideline-show-code-actions t)
    (setq lsp-ui-sideline-show-hover nil)
    (setq lsp-ui-sideline-show-diagnostics t)
    )
           ;; lsp-ui-doc
    ;;        ("M-i" . lsp-ui-doc-focus-frame))
    ;;  ("s-i" . my/toggle-lsp-ui-doc))
    ;; :preface
    ;; (defun my/toggle-lsp-ui-doc ()
    ;;   (interactive)
    ;;   (if lsp-ui-doc-mode
    ;;       (lsp
    ;;         (progn-ui-doc-mode -1)
    ;;         (lsp-ui-doc--hide-frame))
    ;;     (lsp-ui-doc-mode 1))))
#+end_src

#+RESULTS:
: lsp-ui-doc-show

*** =lsp-treemacs=

[[https://github.com/emacs-lsp/lsp-treemacs][More Information]]

#+begin_src emacs-lisp
  (use-package lsp-treemacs
    :commands lsp-treemacs-errors-list
    :config
    (lsp-treemacs-sync-mode 1))
#+end_src

*** =lsp-ivy=

[[https://github.com/emacs-lsp/lsp-ivy][More Informatino]]

#+begin_src emacs-lisp
  (use-package lsp-ivy
    :commands lsp-ivy-workspace-symbol)
#+end_src

** =company=
*** =company-mode=

#+begin_src emacs-lisp
  (use-package company
    :diminish company-mode
    :hook
    (after-init . global-company-mode)
    :bind
    ((:map company-active-map
           ("C-n" . company-select-next)
           ("C-p" . company-select-previous))
     (:map company-search-map
           ("C-n" . company-select-next)
           ("C-p" . company-select-previous)))
    :config
    (setq company-minimum-prefix-length 1)
    (setq company-idle-delay 0)
    (setq company-echo-delay 5)
    ;; (setq company-tooltip-idle-delay 0.0)
    ;; (setq company-tooltip-align-annotations t)
    (setq company-require-match nil)
    (setq company-show-numbers t)
    (setq company-dabbrev-downcase nil) ;; case insensitive for dabbrev backend
    (global-company-mode 1)
    ;; Don't use company in debugger mode
    (setq company-global-modes '(not gud-mode)))
#+end_src

*** =company-box=
[[https://github.com/sebastiencs/company-box#installation][More Information]]
#+begin_src emacs-lisp
  (use-package company-box
    :diminish
    :hook
    (company-mode . company-box-mode)
    :config
    (setq company-box-doc-enable t)
    (setq company-box-doc-delay 0.2)
    )
#+end_src

*** =company-quickhelp=
[[https://github.com/company-mode/company-quickhelp][More Information]]

#+begin_src emacs-lisp :tangle no
  (use-package pos-tip)

  (use-package company-quickhelp
    :after company
    :config
    (setq company-quickhelp-idle-delay 0.2)
    (company-quickhelp-mode 1))
#+end_src

*** =company-tabnine=
- [[https://github.com/TommyX12/company-tabnine][More Information]]
- [[https://github.com/MatthewZMD/.emacs.d#company-tabnine][Config from MatthewZMD]]

#+begin_src emacs-lisp :tangle no
  (use-package company-tabnine
    :defer 1
    :custom
    (company-tabnine-max-num-results 9)
    :init
    (defun company-tabnine-toggle (&optional enable)
      "Enable/Disable TabNine. If ENABLE is non-nil, definitely enable it."
      (interactive)
      (if (or enable (not (memq 'company-tabnine company-backends)))
          (progn
            (add-hook 'lsp-after-open-hook #'lsp-after-open-tabnine)
            (add-to-list 'company-backends #'company-tabnine)
            (when (bound-and-true-p lsp-mode) (lsp-after-open-tabnine))
            (message "TabNine enabled."))
        (setq company-backends (delete 'company-tabnine company-backends))
        (setq company-backends (delete '(company-capf :with company-tabnine :separate) company-backends))
        (remove-hook 'lsp-after-open-hook #'lsp-after-open-tabnine)
        (company-tabnine-kill-process)
        (message "TabNine disabled.")))
    (defun company//sort-by-tabnine (candidates)
      "Integrate company-tabnine with lsp-mode"
      (if (or (functionp company-backend)
              (not (and (listp company-backend) (memq 'company-tabnine company-backends))))
          candidates
        (let ((candidates-table (make-hash-table :test #'equal))
              candidates-lsp
              candidates-tabnine)
          (dolist (candidate candidates)
            (if (eq (get-text-property 0 'company-backend candidate)
                    'company-tabnine)
                (unless (gethash candidate candidates-table)
                  (push candidate candidates-tabnine))
              (push candidate candidates-lsp)
              (puthash candidate t candidates-table)))
          (setq candidates-lsp (nreverse candidates-lsp))
          (setq candidates-tabnine (nreverse candidates-tabnine))
          (nconc (seq-take candidates-tabnine 3)
                 (seq-take candidates-lsp 6)))))
    (defun lsp-after-open-tabnine ()
      "Hook to attach to `lsp-after-open'."
      (setq-local company-tabnine-max-num-results 3)
      (add-to-list 'company-transformers 'company//sort-by-tabnine t)
      (add-to-list 'company-backends '(company-capf :with company-tabnine :separate)))
    :hook
    (kill-emacs . company-tabnine-kill-process)
    :config
    (company-tabnine-toggle t))
#+end_src

** =smartparens=
[[https://github.com/Fuco1/smartparens][More Information]]

#+begin_src emacs-lisp
  (use-package smartparens
    :init
    (progn
      (smartparens-global-mode 1)
      (show-smartparens-global-mode 1))
    :config
    (progn
      (setq smartparens-strict-mode t)
      (setq sp-show-pair-from-inside nil)
      (sp-local-pair 'emacs-lisp-mode "`" nil :when '(sp-in-string-p))))
#+end_src

* Python

Some python settings. Setup jupyter keybindings.

#+begin_src emacs-lisp
  (defun my/jupyter-load-file ()
    "Send current buffer to jupyter kernel by default"
    (interactive)
    (jupyter-load-file (buffer-file-name)))

  (use-package python
    :hook
    (python-mode . (lambda () ;; emulate python-shell-send-buffer
                     (setq indent-tabs-mode nil)
                     (display-fill-column-indicator-mode) ;; display column
                     (unbind-key "C-c C-l" jupyter-repl-interaction-mode-map)
                     (bind-key "C-c C-c" 'my/jupyter-load-file jupyter-repl-interaction-mode-map)
                     (add-hook 'before-save-hook #'lsp-format-buffer t t)))
    :config
    ;; silence indentation guesses
    (setq python-indent-guess-indent-offset-verbose nil))
#+end_src

** =lsp-pyright=

#+begin_src emacs-lisp
  (use-package lsp-pyright)
#+end_src
** =conda=

This package lets you activate your conda environments. The setup works for miniconda installed by hombre.

[[https://github.com/necaris/conda.el][More Information]]

Usage:
- ~M-x conda-env-activate~
- ~M-x conda-env-deactivate~

#+begin_src emacs-lisp
  (use-package conda
    :hook
    (python-mode . (lambda () (conda-env-activate "py3")))
    :config
    (conda-env-initialize-interactive-shells) ;; interactive shell support
    ;; (conda-env-initialize-eshell)             ;; eshell support
    ;; (conda-env-autoactivate-mode t)           ;; autoactivate
    (setq conda-env-home-directory "/usr/local/Caskroom/miniconda/base/")
    (setq conda-anaconda-home "/usr/local/Caskroom/miniconda/base/"))
#+end_src

** =numpydoc=
[[https://github.com/douglasdavis/numpydoc.el][More Information]]
#+begin_src emacs-lisp
  (use-package numpydoc
    :after python
    :bind (:map python-mode-map
                ("C-c C-n" . numpydoc-generate))
    :config
    (setq numpydoc-insert-examples-block nil))
#+end_src

** =emacs-jupyter=
[[https://github.com/nnicandro/emacs-jupyter][More Information]]

#+begin_src emacs-lisp
  (use-package jupyter
    :bind
    (:map python-mode-map
          ("C-c C-p" . jupyter-run-repl))
    :init
    (setq jupyter-repl-allow-RET-when-busy t)
    (setq jupyter-repl-echo-eval-p t)) ;; show plots
#+end_src

** Cython
#+begin_src emacs-lisp
  (use-package cython-mode)
#+end_src

* CPP
* Java
** =lsp-java=
=lsp-mode= for =java=
[[https://emacs-lsp.github.io/lsp-java/][More Information]]

#+begin_src emacs-lisp
  (use-package lsp-java)
#+end_src

** =java-one-click-run=
[[https://github.com/MatthewZMD/java-one-click-run][More Information]]
#+begin_src emacs-lisp :tangle no
  (defun my/java-one-click-run ()
    "Go to previous window after running"
    (interactive)
    (java-one-click-run)
    (select-window (previous-window)))

  (use-package java-one-click-run
    :load-path "~/.emacs.d/site-elisp/java-one-click-run/"
    :init (use-package shell-here)
    :hook
    (java-mode . (lambda () ;; compile and run java program with C-c C-c
                   (unbind-key "C-c C-C" lsp-mode-map)
                   (bind-key "C-c C-c" 'my/java-one-click-run java-mode-map))))
#+end_src
* Golang
#+begin_src emacs-lisp
  (use-package go-mode
    :hook
    (go-mode . (lambda()
                 (add-hook 'before-save-hook #'lsp-format-buffer t t)
                 (add-hook 'before-save-hook #'lsp-organize-imports t t))))
#+end_src

* Markdown
** =markdown-mode=
[[https://jblevins.org/projects/markdown-mode/][More Information]]

#+begin_src emacs-lisp
  (use-package markdown-mode
    :ensure t
    :mode (("README\\.md\\'" . gfm-mode)
           ("\\.md\\'" . markdown-mode)
           ("\\.markdown\\'" . markdown-mode))
    :init (setq markdown-command "multimarkdown"))
#+end_src

** =grip=
[[https://github.com/seagle0128/grip-mode][More Information]]
#+begin_src emacs-lisp :tangle no
  (use-package grip-mode
    ;; :init
    ;; (progn
    ;;   (require 'auth-source)
    ;;   (let ((credential (auth-source-user-and-password "api.github.com")))
    ;;     (setq grip-github-user (car credential)
    ;;           grip-github-password (cadr credential))))
    :bind (:map markdown-mode-command-map
                ("g" . grip-mode)))

#+end_src

* RTF
#+begin_src emacs-lisp
  (use-package rtf-mode
    :config
    (add-to-list 'auto-mode-alist
                 '("\\.rtf$" . rtf-mode))
    )
#+end_src

* SQL
** =pgformatter=
[[https://arjanvandergaag.nl/blog/using-emacs-as-a-database-client.html][More Information]]

*Prerequisite*
#+begin_src shell :tangle no
  brew install pgformatter
#+end_src

#+begin_src emacs-lisp :tangle no
  (use-package sqlformat
    :commands (sqlformat sqlformat-buffer sqlformat-region)
    :hook (sql-mode . sqlformat-on-save-mode)
    :init
    (setq sqlformat-command 'pgformatter
          sqlformat-args '("-s2" "-g" "-u1")))
#+end_src

* Web Development
** Javascript
*** RSJX mode
#+begin_src emacs-lisp
  (use-package rjsx-mode
    :mode
    (("\\.js\\'" . rjsx-mode)
     ("\\.tsx\\'" . rjsx-mode)
     ("\\.ts\\'" . rjsx-mode)))
  #+end_src

*** Tide
#+begin_src emacs-lisp
  (defun my/setup-tide-mode()
    "Setup function for tide"
    (interactive)
    (tide-setup)
    (flycheck-mode +1)
    (setq flycheck-check-syntax-automatically '(save mode-enabled))
    (tide-hl-identifier-mode +1))

  (use-package tide
    :after
    (rjsx-mode)
    :hook
    (rjsx-mode . my/setup-tide-mode))
#+end_src

*** Prettier
#+begin_src emacs-lisp
  (use-package prettier-js
    :after
    (rjsx-mode)
    :hook
    (rjsx-mode . prettier-js-mode))
#+end_src
** =CSS=
*** =lsp-css=
[[https://emacs-lsp.github.io/lsp-mode/page/lsp-css/][More Information]]

*Install:*
- ~M-x lsp-install-server css-ls~
#+begin_src emacs-lisp
  (use-package css-mode
    :hook
    (css-mode . lsp))
#+end_src

** =HTML=
[[https://emacs-lsp.github.io/lsp-mode/page/lsp-html/][More Information]]

*Install:*
- ~M-x lsp-install-server html-ls~
#+begin_src emacs-lisp :tangle no
  (use-package mhtml-mode
    :hook
    (mhtml-mode . (lambda()
                    (lsp)
                    (unbind-key "C-c C-v" mhtml-mode-map)
                    (bind-key "C-c C-v" 'my/browse-url-of-buffer-with-chrome))))
#+end_src

** =JSON=

[[https://github.com/joshwnj/json-mode][More Information]]

*Install*
- ~M-x lsp-install-server json-ls~
#+begin_src emacs-lisp
  (use-package json-mode
    :mode "\\.json\\'"
    :hook
    (json-mode . lsp))
#+end_src

** =YAML=
[[https://github.com/yoshiki/yaml-mode][More Information]]
#+begin_src emacs-lisp
  (use-package yaml-mode
    :mode
    ("\\.ya?ml\\'"))
#+end_src
** =CSV=
[[https://github.com/jcf/emacs.d/blob/master/init-languages.org#csv][More Information]]
#+begin_src emacs-lisp
  (use-package csv-mode
    :mode "\\.[Cc][Ss][Vv]\\'"
    ;; :init (setq csv-separators '("," ";" "|" " "))
    :config
    (setq csv-separators '(",")))
#+end_src

* Appearance
** Icons
*** =all-the-icons=

 All The Icons, a utility package to collect various Icon Fonts. Enable only in GUI Emacs.

[[https://github.com/domtronn/all-the-icons.el][More Information]]

#+begin_src shell :tangle no
  M-x all-the-icons-install-fonts
#+end_src

 #+begin_src emacs-lisp
   (use-package all-the-icons)
 #+end_src

*** =all-the-icons-ivy-rich=

[[https://github.com/seagle0128/all-the-icons-ivy-rich][More Information]]

  #+begin_src emacs-lisp
    (use-package all-the-icons-ivy-rich
      :config
      (all-the-icons-ivy-rich-mode 1))
  #+end_src

*** =ivy-rich=

More friendly interface for ivy.
[[https://github.com/Yevgnen/ivy-rich][More Information]]

#+begin_src emacs-lisp
  (use-package ivy-rich
    :config
    (ivy-rich-mode 1)
    (setcdr (assq t ivy-format-functions-alist) #'ivy-format-function-line))
#+end_src

*** =all-the-icons-dired=

#+begin_src emacs-lisp
  (use-package all-the-icons-dired
    :diminish
    :custom-face
    (all-the-icons-dired-dir-face ((t (:foreground nil))))
    :hook
    (dired-mode . all-the-icons-dired-mode))
#+end_src

*** =mode-icons=

#+begin_src emacs-lisp
  (use-package mode-icons
    :config
    (mode-icons-mode))
#+end_src

** Themes
*** Doom Theme

Doom Themes, an UI plugin and pack of themes

[[https://github.com/hlissner/emacs-doom-themes][More Information]]

#+begin_src emacs-lisp
  (use-package doom-themes
    :custom-face
    (cursor ((t (:background "DarkRed"))))
    :config
    (load-theme 'doom-gruvbox t)

    (doom-themes-visual-bell-config)  ;; flashing mode-line on errors

    ;; (setq doom-themes-treemacs-theme "doom-colors") ; use the colorful treemacs theme
    ;; (doom-themes-treemacs-config)

    (doom-themes-org-config)          ;; Corrects (and improves) org-mode's native fontification.
    )

    ;; (load-theme 'doom-city-lights t))
    ;; (load-theme 'doom-molokai t)
    ;; (load-theme 'doom-sourcerer t)
    ;; (load-theme 'doom-tomorrow-night t)
    ;; (load-theme 'doom-gruvbox t)
#+end_src

*** Doom Modeline

Doom Modeline, a modeline from DOOM Emacs, but more powerful and faster.

[[https://github.com/seagle0128/doom-modeline][More Information]]

#+begin_src emacs-lisp
  (use-package doom-modeline
    :init
    (doom-modeline-mode 1)
    :config
    ;; (setq inhibit-compacting-font-caches t)
    (setq doom-modeline-minor-modes nil)
    (setq doom-modeline-icon t)
    (setq doom-modeline-major-mode-color-icon t)
    (setq doom-modeline-height 15))
#+end_src

*** Other Themes

#+begin_src emacs-lisp
  ;; (use-package spacemacs-theme
  ;;   :config
  ;;   (load-theme spacemacs-theme-light))
  ;; ;; (use-package solarized-theme)
  ;; (use-package darktooth-theme)
  ;; (use-package kaolin-themes)
  ;; (use-package gruvbox-theme
  ;;   :config
  ;;   (load-theme 'gruvbox))
#+end_src

** =beacon=

[[https://github.com/Malabarba/beacon][More Information]]

#+begin_src emacs-lisp
  (use-package beacon
    :config
    (beacon-mode 1)
    (setq beacon-color "#39FF14"))
#+end_src

** =rainbow-delimiters=

[[https://github.com/Fanael/rainbow-delimiters][More Information]]

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook
    (prog-mode . rainbow-delimiters-mode))
#+end_src

** =dimmer.el=

[[https://github.com/gonewest818/dimmer.el][More Information]]

#+begin_src emacs-lisp
  (use-package dimmer
    :config
    (setq dimmer-fraction 0)
    (dimmer-mode t))
#+end_src

** =dashboard=

=dashboard= is an extensible emacs startup screen showing you what's most important.
[[https://github.com/emacs-dashboard/emacs-dashboard][More Information]]

#+begin_src emacs-lisp :tangle no
  ;; Dependency
  (use-package page-break-lines)

  (use-package dashboard
    :config
    (setq show-week-agenda-p t)
    (dashboard-setup-startup-hook))
#+end_src

* Org
#+begin_src emacs-lisp
  ;; Tangle on config file
  (defun my/tangle-emacs-config ()
    "If the current file is this file, the code blocks are tangled"
    (when (equal (buffer-file-name) (expand-file-name "~/.emacs.d/my-literate-emacs-configuration.org"))
      (org-babel-tangle nil "~/.emacs.d/init.el")))

  (use-package org
    :straight (:type built-in)
    :hook
    (after-save . my/tangle-emacs-config)
    (org-mode . (lambda ()
                  (flyspell-mode)
                  (display-fill-column-indicator-mode)
                  (auto-fill-mode)
                  ))
    :init
    (use-package org-indent :straight (:type built-in))
    :config
    ;; -------------------- Org Agenda --------------------
    ;; Org settings
    (setq org-directory "~/Documents/Org") ;; Set default org directory
    (setq org-default-notes-file (concat org-directory "/tasks.org")) ;; Set default org capture file
    ;; Org agenda
    (setq org-todo-keywords
          '((sequence "TODO"  "|" "DONE" "CANCELED")))
    (setq org-agenda-files '("~/Documents/Org/"))
    (setq org-agenda-window-setup 'current-window)
    ;; org capture
    (setq org-capture-templates
          '(("a" "Assignment" entry
             (file+headline "~/Documents/Org/Academic.org" "Assignments")
             "* TODO %?\n")
            ("E" "Exam" entry
             (file+headline "~/Documents/Org/Academic.org" "Exams")
             "* TODO %?\n")
            ("P" "Project" entry
             (file+headline "~/Documents/Org/Academic.org" "Projects")
             "* TODO %?\n")))
    ;; -------------------- Evaluation of Source Blocks --------------------
    ;; Do not confirm when evaluating code blocks
    (setq org-confirm-babel-evaluate nil)
    ;; Run/highlight code using babel in org-mode
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((python . t)
       (js . t)
       (latex . t)
       (jupyter . t)
       (sql . t)
       (shell . t)
       (emacs-lisp . t)))
    ;; How to edit source code blocks: [plain, current-window, split-window-below, other-window, other-frame]
    (setq org-src-window-setup 'current-window)
    ;; Edit source code blocks menu
    (setq org-structure-template-alist
          '(("a" . "export ascii\n")
            ("c" . "center\n")
            ("C" . "comment\n")
            ("e" . "src emacs-lisp\n")
            ("E" . "export")
            ("h" . "export html\n")
            ("l" . "src latex\n")
            ("q" . "quote\n")
            ("p" . "src python\n")
            ("s" . "src sql")
            ("v" . "verse\n")))
    ;; -------------------- Various Behavior --------------------
    ;; Follow link when hitting return
    (setq org-return-follows-link t)
    ;; -------------------- Latex Exports --------------------
    ;; auctex
    (use-package tex
      :straight auctex)
    ;; Remove logfiles
    (setq org-latex-logfiles-extensions '(
                                          ;; Default settings
                                          "aux" "bcf" "blg" "fdb_latexmk" "fls" "figlist" "idx" "log" "nav" "out" "ptc" "run.xml" "snm" "toc" "vrb" "xdv"
                                          ;; Added settings
                                          "bbl" "lof" "lot" "tex" "glo" "ist" "glg" "gls" "acn" "acr" "alg"
                                          ))
    (setq org-latex-remove-logfiles t)
    ;; Set default figure position
    (setq org-latex-default-figure-position "H")
    ;; Set default caption position
    (setq org-latex-caption-above nil) ;; '("table" "image")
    ;; Set default export to async
    (setq org-export-in-background t)
    ;; Remove default header exports
    (setq org-export-with-title nil
          org-export-with-date nil
          org-export-with-creator nil
          org-export-with-toc nil
          )
    ;; add glossary and acronyms
    (add-to-list 'org-export-before-parsing-hook 'org-ref-acronyms-before-parsing)
    (add-to-list 'org-export-before-parsing-hook 'org-ref-glossary-before-parsing)
    ;; Latex compilation
    ;; (setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f"))
    (setq org-latex-pdf-process
          '("pdflatex -interaction nonstopmode -output-directory %o %f"
            "bibtex %b"
            "makeglossaries %b"
            "pdflatex -interaction nonstopmode -output-directory %o %f"
            "pdflatex -interaction nonstopmode -output-directory %o %f"))
    ;; Latex classes
    (setq org-latex-classes
          '(("article"
             "
  \\documentclass[10pt]{article}
  % Setup
  \\usepackage[english]{babel}
  \\usepackage[utf8]{inputenc}
  \\usepackage{import}
  \\usepackage[hidelinks]{hyperref}
  \\usepackage{url}
  \\hypersetup{colorlinks=false}
  % Geometry
  \\usepackage[a4paper, width=150mm, top=25mm, bottom=25mm]{geometry}
  \\usepackage{parskip}
  \\setlength{\\parindent}{0pt}
  \\setlength{\\parskip}{\\baselineskip}
  % Math
  \\usepackage{amsmath}
  \\usepackage{amssymb}
  % Tables
  \\usepackage{array}
  \\usepackage{multirow}
  \\usepackage{longtable}
  % Color
  \\usepackage{xcolor}
  % Figures
  \\usepackage{graphicx} % To show figures
  \\usepackage{wrapfig}  % Wrap text around figures
  \\usepackage{subcaption}
  \\usepackage{rotating}
  % Others
  \\usepackage{float}
  \\usepackage{lastpage}
  \\usepackage[normalem]{ulem}
  \\usepackage{capt-of}
  \\usepackage{csquotes}
  \\usepackage{enumitem}
  \\usepackage{ragged2e}
  \\setlist{nosep} % or \setlist{noitemsep} to leave space around whole list
  % TOC and Appendix
  \\usepackage{appendix}
  \\usepackage[nottoc]{tocbibind}
    \\usepackage[acronyms, section]{glossaries}
    \\makeglossaries
  % Footers and Headers
  \\usepackage{fancyhdr}
  \\pagestyle{fancy}
  \\fancyhf{}
  \\fancyfoot[C]{\\thepage}
  \\renewcommand{\\footrulewidth}{0.1pt}
  % Bibliography
  \\usepackage{natbib}
  \\makeatletter
  \\renewcommand{\\maketitle}{%
  \\begingroup\\parindent0pt
  \\Large{\\bfseries\\@title}\\newline
  \\normalsize{\\bfseries\\@author}\\newline
  \\normalsize{\\@date}\\vspace{-0.2cm}\\newline
  \\noindent\\makebox[\\textwidth]{\\rule{\\textwidth}{0.4pt}}
  \\endgroup\\@afterindentfalse\\@afterheading}
  \\makeatother
  [NO-DEFAULT-PACKAGES]
  "
             ("\\section{%s}" . "\\section*{%s}")
             ("\\subsection{%s}" . "\\subsection*{%s}")
             ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
             ("\\paragraph{%s}" . "\\paragraph*{%s}")
             ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))

            ("report"
             "
  \\documentclass[10pt]{report}
  % Setup
  \\usepackage[english]{babel}
  \\usepackage[utf8]{inputenc}
  \\usepackage{import}
  \\usepackage[hidelinks]{hyperref}
  \\usepackage{url}
  \\hypersetup{colorlinks=false}
  % Geometry
  \\usepackage[a4paper, width=150mm, top=25mm, bottom=25mm]{geometry}
  \\usepackage{parskip}
  \\setlength{\\parindent}{0pt}
  \\setlength{\\parskip}{\\baselineskip}
  % Math
  \\usepackage{amsmath}
  \\usepackage{amssymb}
  % Tables
  \\usepackage{array}
  \\usepackage{multirow}
  \\usepackage{longtable}
  % Color
  \\usepackage{xcolor}
  % Figures
  \\usepackage{graphicx} % To show figures
  \\usepackage{wrapfig}  % Wrap text around figures
  \\usepackage{subcaption}
  \\usepackage{rotating}
  % Others
  \\usepackage{float}
  \\usepackage{lastpage}
  \\usepackage[normalem]{ulem}
  \\usepackage{capt-of}
  \\usepackage{csquotes}
  \\usepackage{enumitem}
  \\usepackage{ragged2e}
  \\setlist{nosep} % or \setlist{noitemsep} to leave space around whole list
  % TOC and Appendix
  \\usepackage{appendix}
  \\usepackage[nottoc]{tocbibind}
    \\usepackage[acronyms, section]{glossaries}
    \\makeglossaries
  % Footers and Headers
  \\usepackage{fancyhdr}
  \\pagestyle{fancy}
  \\fancyhf{}
  \\fancyfoot[C]{\\thepage}
  \\renewcommand{\\footrulewidth}{0.1pt}
  % Bibliography
  \\usepackage{natbib}

  [NO-DEFAULT-PACKAGES]
  "

             ("\\chapter{%s}" . "\\chapter*{%s}")
             ("\\section{%s}" . "\\section*{%s}")
             ("\\subsection{%s}" . "\\subsection*{%s}")
             ("\\subsubsection{%s}" . "\\subsubsection*{%s}"))

            ("book" "\\documentclass[10pt]{book}"
             ("\\part{%s}" . "\\part*{%s}")
             ("\\chapter{%s}" . "\\chapter*{%s}")
             ("\\section{%s}" . "\\section*{%s}")
             ("\\subsection{%s}" . "\\subsection*{%s}")
             ("\\subsubsection{%s}" . "\\subsubsection*{%s}")))
          )
    ;; -------------------- Bibliography --------------------
    (setq org-latex-prefer-user-labels t)
    (use-package bibtex
      :straight (:type built-in)
      :init
      (use-package ivy-bibtex)
      (setq bibtex-completion-bibliography '("~/Documents/Org/Bibliography/Master.bib"))
      (setq bibtex-completion-library-path nil)
      (setq bibtex-completion-notes-path nil)
      (setq bibtex-completion-pdf-field "file")
      (setq bibtex-completion-pdf-open-function
            (lambda (fpath)
              (call-process "open" nil 0 nil fpath))))

    (use-package org-ref
      :bind
      (:map bibtex-mode-map
            ("H-]" . org-ref-bibtex-hydra/body)
            :map org-mode-map
            ("C-c ]" . org-ref-insert-link)
            ("s-]" . org-ref-insert-link-hydra/body))
      :init
      (use-package org-ref-ivy :straight (:type built-in))
      (setq org-ref-insert-link-function 'org-ref-insert-link-hydra/body
            org-ref-insert-cite-function 'org-ref-cite-insert-ivy
            org-ref-insert-label-function 'org-ref-insert-label-link
            org-ref-insert-ref-function 'org-ref-insert-ref-link))
    ;; -------------------- PDF --------------------
    (use-package pdf-tools
      :init
      (use-package tablist)

      :mode ("\\.pdf\\'" . pdf-view-mode)
      :bind
      (:map pdf-view-mode-map
            ("C-s" . isearch-forward))
      :config
      (pdf-loader-install)
      (setq pdf-view-display-size 'fit-page)
      )
    (use-package pdf-view-restore
      :after pdf-tools
      :hook
      (pdf-view-mode . pdf-view-restore-mode)
      :config
      (setq pdf-view-restore-filename "~/.emacs.d/.pdf-view-restore")
      )
    ;; -------------------- Org Download --------------------
    ;; https://github.com/abo-abo/org-download
    (use-package org-download
      :config
      (setq org-download-display-inline-images t))
    ;; -------------------- Beautifying Org Mode --------------------
    ;; Emphasis - disable strikethrough
    (setq org-emphasis-alist '(("*" bold)
                               ("/" italic)
                               ("_" underline)
                               ("=" org-verbatim verbatim)
                               ("~" org-code verbatim)
                               ("+" (:strike-through nil))))
    ;; Emphasis - hide markers
    (setq org-hide-emphasis-markers t)
    ;; Org-Superstar - https://github.com/integral-dw/org-superstar-mode
    (use-package org-superstar
      :hook
      (org-mode . (lambda () (org-superstar-mode 1)))
      :config
      (setq org-superstar-headline-bullets-list '("◉" "◈" "○" "▷"))
      ;; Do not cycle after bottom level
      (setq org-superstar-cycle-headline-bullets nil)
      )
    ;; Fonts and Section Title color
    (let* ((variable-tuple
            (cond ((x-list-fonts "ETBembo")         '(:font "ETBembo"))
                  ((x-list-fonts "Source Sans Pro") '(:font "Source Sans Pro"))
                  ((x-list-fonts "Lucida Grande")   '(:font "Lucida Grande"))
                  ((x-list-fonts "Verdana")         '(:font "Verdana"))
                  ((x-family-fonts "Sans Serif")    '(:family "Sans Serif"))
                  (nil (warn "Cannot find a Sans Serif Font.  Install Source Sans Pro."))))
           (base-font-color     (face-foreground 'default nil 'default))
           (headline           `(:inherit default :weight bold :foreground ,base-font-color)))

      (custom-theme-set-faces
       'user
       `(org-level-8 ((t (,@headline ,@variable-tuple))))
       `(org-level-7 ((t (,@headline ,@variable-tuple))))
       `(org-level-6 ((t (,@headline ,@variable-tuple))))
       `(org-level-5 ((t (,@headline ,@variable-tuple))))
       `(org-level-4 ((t (,@headline ,@variable-tuple :forground "RoyalBlue1"   :height 1.1))))
       `(org-level-3 ((t (,@headline ,@variable-tuple :foreground "firebrick3" :height 1.25))))
       `(org-level-2 ((t (,@headline ,@variable-tuple :foreground "green3" :height 1.5))))
       `(org-level-1 ((t (,@headline ,@variable-tuple :foreground "DarkOrange2" :height 1.75))))
       `(org-document-title ((t (,@headline ,@variable-tuple :height 2.0 :underline nil))))))
    ;; Indentation
    (setq org-startup-indented nil)
    ;; prettify symbols
    (setq org-pretty-entities nil)
    ;; images - set width
    (setq org-startup-with-inline-images t
          org-image-actual-width '(300))

    )
#+end_src

#+RESULTS:
| (lambda nil (flyspell-mode) (display-fill-column-indicator-mode) (auto-fill-mode)) | (lambda nil (org-superstar-mode 1)) | (closure (bootstrap-version t) nil (flyspell-mode) (display-fill-column-indicator-mode) (auto-fill-mode)) | (closure (bootstrap-version t) nil (org-superstar-mode 1)) | org-ref-org-menu | jupyter-org-interaction-mode | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-show-all append local] 5] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes | #[0 \301\211\207 [imenu-create-index-function org-imenu-get-tree] 2] | (closure ((mode . org-mode-hook) (--dolist-tail--) bootstrap-version t) nil (display-line-numbers-mode 0)) |


** Bibliography

* Writing
** =flyspell=
#+begin_src emacs-lisp
  (use-package flyspell
    :config
    (setenv
     "DICPATH"
     (concat (getenv "HOME") "/Library/Spelling"))
    (setenv "DICTIONARY" "en_US")
    ;; Tell ispell-mode to use hunspell.
    (setq ispell-program-name "hunspell")
    (setq-default ispell-hunspell-dict-paths-alist
                  '(("en_US" "~/Library/Spelling/en_US.aff"))))

  (defun my/save-word-to-personal-dictionary ()
    "Save word to personal dictionary"
    (interactive)
    (let ((current-location (point))
          (word (flyspell-get-word)))
      (when (consp word)
        (flyspell-do-correct 'save nil (car word) current-location (cadr word) (caddr word) current-location))))

  ;; Remap
  (unbind-key "C-c $" flyspell-mode-map)
  (bind-key "C-c $" 'my/save-word-to-personal-dictionary flyspell-mode-map)

  ;; Norsk tastatur
  (bind-key "C-ø" 'flyspell-auto-correct-previous-word flyspell-mode-map)
#+end_src

** =synosaurus=

Synosaurus is a thesaurus fontend for Emacs with pluggable backends.
[[https://github.com/hpdeifel/synosaurus][More Information]]

#+begin_src emacs-lisp
  (use-package synosaurus
    :init
    (synosaurus-mode)
    :hook
    (text-mode . synosaurus-mode)
    :config
    (setq synosaurus-choose-method 'ido))
#+end_src

** =guess-language=
=guess-language= is an Emacs minor mode that detects the language of what you're
typing. Automatically switches the spell checker and typo-mode if present.
[[https://github.com/tmalsburg/guess-language.el][More Information]]

#+begin_src emacs-lisp :tangle no
  (use-package guess-language
    :hook
    (text-mode . guess-language-mode)
    :config
    (setq guess-language-langcodes '((en . ("en_US" "English"))
                                     (no . ("nb_NO" "Norwegian"))))
    (setq guess-language-languages '(en no))
    (setq guess-language-min-paragraph-length 45))
#+end_src

** languagetool
#+begin_src emacs-lisp
  (use-package langtool
    :init
    (setq langtool-default-language "en-US")
    (setq langtool-bin "/usr/local/bin/languagetool")
    )
#+end_src

** =lsp-grammarly=
[[https://github.com/emacs-grammarly/lsp-grammarly][More Information]]
#+begin_src emacs-lisp :tangle no
  (use-package lsp-grammarly
    :hook (org-mode . (lambda ()
                        (require 'lsp-grammarly)
                        (lsp))))
#+end_src

** =unfill-paragraph=
#+begin_src emacs-lisp
      ;;; Stefan Monnier <foo at acm.org>. It is the opposite of fill-paragraph
      (defun unfill-paragraph (&optional region)
        "Takes a multi-line paragraph and makes it into a single line of text."
        (interactive (progn (barf-if-buffer-read-only) '(t)))
        (let ((fill-column (point-max))
              ;; This would override `fill-column' if it's an integer.
              (emacs-lisp-docstring-fill-column t))
          (fill-paragraph nil region)))
#+end_src

* Elisp Functions
** Read content of file

#+begin_src emacs-lisp
  (defun my/get-file-content-as-string (filePath)
    "Return filePath's content as string."
    (with-temp-buffer
      (insert-file-contents filePath)
      (buffer-string)))
#+end_src

** Edit Configuration File

#+begin_src emacs-lisp
  (defun my/edit-config ()
    "Opens the my-literate-emacs-configuration.org file."
    (interactive)
    (find-file "~/.emacs.d/my-literate-emacs-configuration.org"))
#+end_src

** Open bib file
#+begin_src emacs-lisp
  (defun my/bib ()
    "Opens the master bibliography file."
    (interactive)
    (find-file "~/Documents/Org/Bibliography/Master.bib"))
#+end_src

** Switching jupyter kernel in conda environment

[[https://sqrtminusone.xyz/posts/2021-05-01-org-python/][More Information]]

#+begin_src emacs-lisp
  (defun my/jupyter-refresh-kernelspecs ()
    "Refresh Jupyter kernelspecs"
    (interactive)
    (jupyter-available-kernelspecs t))
#+end_src

** Insert Org Startup Template

#+begin_src emacs-lisp
  (defun my/org-startup ()
    (interactive)
    (insert "#+TITLE: \n#+AUTHOR: Simen Omholt-Jensen\n#+OPTIONS: toc:nil\n"))
#+end_src

#+begin_src emacs-lisp
  (defun my/org-notebook-startup ()
    (interactive)
    (insert "#+TITLE: \n#+AUTHOR: Simen Omholt-Jensen\n#+OPTIONS: toc:nil\n#+STARTUP: overview\n")
    (insert "#+PROPERTY: header-args:python :session notebook :kernel notebook :async yes :results output :exports both :eval never-export\n\n")
    (insert "** Imports\n #+begin_src python\n")
    (insert "  import numpy as np\n  import pandas as pd\n  import matplotlib.pyplot as plt\n")
    (insert "  import matplotlib as mpl\n  mpl.rcParams['figure.facecolor']='w'\n")
    (insert "  #+end_src\n\n"))
#+end_src

** Open HTML buffer in Chrome
#+begin_src emacs-lisp
  (defun my/browse-url-of-buffer-with-chrome ()
    "Same as `browse-url-of-buffer` but using chrome"
    (interactive)
    ;; (shell-command (concat "open -a 'Google Chrome.app' file://" buffer-file-name)))
   (shell-command (concat "open -a 'Google Chrome.app' " buffer-file-name)))
#+end_src

** transpose windows
[[https://emacs.stackexchange.com/questions/5371/how-to-change-emacs-windows-from-vertical-split-to-horizontal-split][More Information]]
#+begin_src emacs-lisp
  (defun window-split-toggle ()
    "Toggle between horizontal and vertical split with two windows."
    (interactive)
    (if (> (length (window-list)) 2)
        (error "Can't toggle with more than 2 windows!")
      (let ((func (if (window-full-height-p)
                      #'split-window-vertically
                    #'split-window-horizontally)))
        (delete-other-windows)
        (funcall func)
        (save-selected-window
          (other-window 1)
          (switch-to-buffer (other-buffer))))))

  (bind-key "C-x C-t" 'window-split-toggle)
#+end_src

* Tools
** Wireshark
*** =pcap-mode=
[[https://github.com/orgcandman/pcap-mode][More Information]]

#+begin_src emacs-lisp :tangle no
  (use-package pcap-mode
    :mode
    ("\\.pcapng\\'" . pcap-mode)
    :load-path (lambda () (expand-file-name "site-elisp/pcap-mode" user-emacs-directory)))
#+end_src

** Internet
*** =google-this=

[[http://pragmaticemacs.com/emacs/google-search-from-inside-emacs/][More Information]]

#+begin_src emacs-lisp
  (use-package google-this
    :diminish
    :config
    (google-this-mode t))
#+end_src

*** =engine-mode=

#+begin_src emacs-lisp
  (use-package engine-mode
    :config
    (engine-mode t)
    (defengine google
      "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%s"
      :keybinding "g")
    (defengine github
      "https://github.com/search?ref=simplesearch&q=%s")
    (defengine google-maps
      "http://maps.google.com/maps?q=%s"
      :docstring "Mappin' it up.")
    (defengine youtube
      "http://www.youtube.com/results?aq=f&oq=&search_query=%s"
      :keybinding "y"))
#+end_src

** =wgrep=

#+begin_src emacs-lisp
  (use-package wgrep)
#+end_src

** Tramp
#+begin_src emacs-lisp
  (use-package tramp
    :straight (:type built-in)
    :config
    (setq tramp-default-method "ssh")
    )
#+end_src

* Experimental
#+begin_src emacs-lisp



#+end_src

*** =forge=
[[https://emacsair.me/2018/12/19/forge-0.1/][forge]]

** Writing tools to look into
-[[https://people.umass.edu/weikaichen/post/emacs-academic-tools/][emacs-academic-tools]]
- [[https://github.com/nashamri/academic-phrases][academic-phrases]]
- [[https://github.com/gromnitsky/wordnut][wordnut]]
- [[https://github.com/hpdeifel/synosaurus][synosaurus]]
- [[https://github.com/org-roam/org-roam][org-roam]]
  - [[https://rgoswami.me/posts/org-note-workflow/][org-mode notes workflow]]
- =org2blog= to wordspress
- =org-publish=
